name: workout_tracker_app
description: "An app to track your workouts"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.3
  shared_preferences: ^2.5.2
  intl: any
  go_router: ^14.8.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  location: ^8.0.0
  pedometer_2: ^5.0.4
  flutter_command: ^7.2.2
  result_dart: ^2.0.0
  http: ^1.3.0
  permission_handler: ^11.4.0
  flutter_osm_plugin: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.4
  freezed: ^3.0.4

flutter:
  uses-material-design: true
  generate: true
